# Auto-generated by EclipseNSIS Script Wizard
# 9-mar-2011 16.17.45

Name winkhouseDBAgent

RequestExecutionLevel highest

# General Symbol Definitions
!define REGKEY "SOFTWARE\$(^Name)"
!define VERSION 1.1.2
!define COMPANY winkhouse.org
!define URL www.winkhouse.org

# MUI Symbol Definitions
!define MUI_ICON winkhouseDBAgent.ico
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_UNICON unwinkhouseDBAgent.ico
!define MUI_UNFINISHPAGE_NOAUTOCLOSE

# Included files
!include Sections.nsh
!include MUI2.nsh

# Variables
Var StartMenuGroup

# Installer pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE licenza.txt
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# Installer languages
!insertmacro MUI_LANGUAGE Italian

!define FileCopy `!insertmacro FileCopy`
!macro FileCopy FilePath TargetDir
  CreateDirectory `${TargetDir}`
  CopyFiles `${FilePath}` `${TargetDir}`
!macroend

# Installer attributes
OutFile winkhouseDBAgent_Installer.exe
InstallDir $PROGRAMFILES\winkhouseDBAgent
CRCCheck on
XPStyle on
ShowInstDetails show
VIProductVersion 1.1.2.0
VIAddVersionKey /LANG=${LANG_ITALIAN} ProductName winkhouseDBAgent
VIAddVersionKey /LANG=${LANG_ITALIAN} ProductVersion "${VERSION}"
VIAddVersionKey /LANG=${LANG_ITALIAN} CompanyName "${COMPANY}"
VIAddVersionKey /LANG=${LANG_ITALIAN} CompanyWebsite "${URL}"
VIAddVersionKey /LANG=${LANG_ITALIAN} FileVersion "${VERSION}"
VIAddVersionKey /LANG=${LANG_ITALIAN} FileDescription ""
VIAddVersionKey /LANG=${LANG_ITALIAN} LegalCopyright ""
InstallDirRegKey HKLM "${REGKEY}" Path
ShowUninstDetails show

# Installer sections
Section -Main SEC0000
    SetOutPath $INSTDIR
    Delete "$INSTDIR\configuration\*.*"
    Delete "$INSTDIR\plugins\*.*"
    SetOverwrite ifnewer
    File /a /r "C:\Users\michele\workspace\winkhouseDBAgent\deploy\winkhouseDBAgent\winkhouseDBAgent.exe"
    SetOverwrite off
    File /a /r "C:\Users\michele\workspace\winkhouseDBAgent\deploy\winkhouseDBAgent\*.*"
    SetOverwrite off
    File /a "C:\Users\michele\workspace\winkhouseDBAgent\deploy\winkhouseDBAgent\workspace\.metadata\.plugins\winkhouseDBAgent\database.preference"    
    SetOverwrite off
    File /a /r "C:\Users\michele\workspace\winkhouseDBAgent\deploy\winkhouseDBAgent\workspace\.metadata\.plugins\winkhouseDBAgent\winkhouse\*.*"
    WriteRegStr HKLM "${REGKEY}\Components" Main 1
SectionEnd

Section -post SEC0001
    WriteRegStr HKLM "${REGKEY}" Path $INSTDIR
    SetOutPath $INSTDIR
    CreateShortcut "$INSTDIR\winkhouseDBAgent.lnk" '"$INSTDIR\winkhouseDBAgent.exe"'
    CreateShortcut "$INSTDIR\$(^UninstallLink).lnk" '"$INSTDIR\uninstall.exe"'            
    WriteUninstaller $INSTDIR\uninstall.exe
    SetOutPath $SMPROGRAMS\$StartMenuGroup
    ${FileCopy} "$INSTDIR\winkhouseDBAgent.lnk" "$SMPROGRAMS\$StartMenuGroup"
    ${FileCopy} "$INSTDIR\$(^UninstallLink).lnk" "$SMPROGRAMS\$StartMenuGroup"
    ${FileCopy} "$INSTDIR\winkhouseDBAgent.lnk" "$SMSTARTUP" 
#    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\winkhouseDBAgent.lnk" '"$INSTDIR\winkhouseDBAgent.exe"'
#    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\$(^UninstallLink).lnk" '"$INSTDIR\uninstall.exe"'
#    CreateShortcut "$SMSTARTUP\winkhouseDBAgent.lnk" $INSTDIR\winkhouseDBAgent.exe
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayName "$(^Name)"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayVersion "${VERSION}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" Publisher "${COMPANY}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" URLInfoAbout "${URL}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayIcon $INSTDIR\uninstall.exe
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" UninstallString $INSTDIR\uninstall.exe
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoModify 1
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoRepair 1
    Delete "$INSTDIR\winkhouseDBAgent.lnk"
    Delete "$INSTDIR\$(^UninstallLink).lnk"
    Delete "$INSTDIR\winkhouse.script"
    Delete "$INSTDIR\winkhouse.properties"
    Delete "$INSTDIR\database.preference"
    Delete "$INSTDIR\.eclipseproduct"    
SectionEnd

# Macro for selecting uninstaller sections
!macro SELECT_UNSECTION SECTION_NAME UNSECTION_ID
    Push $R0
    ReadRegStr $R0 HKLM "${REGKEY}\Components" "${SECTION_NAME}"
    StrCmp $R0 1 0 next${UNSECTION_ID}
    !insertmacro SelectSection "${UNSECTION_ID}"
    GoTo done${UNSECTION_ID}
next${UNSECTION_ID}:
    !insertmacro UnselectSection "${UNSECTION_ID}"
done${UNSECTION_ID}:
    Pop $R0
!macroend

# Uninstaller sections
Section /o -un.Main UNSEC0000
    RmDir /r /REBOOTOK $INSTDIR
    DeleteRegValue HKLM "${REGKEY}\Components" Main
SectionEnd

Section -un.post UNSEC0001
    DeleteRegKey HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)"
    Delete "$SMPROGRAMS\$StartMenuGroup\winkhouseDBAgent.lnk"
    Delete "$SMSTARTUP\winkhouseDBAgent.lnk"
    Delete "$SMPROGRAMS\$StartMenuGroup\$(^UninstallLink).lnk"    
    Delete /REBOOTOK $INSTDIR\uninstall.exe
    DeleteRegValue HKLM "${REGKEY}" Path
    DeleteRegKey /IfEmpty HKLM "${REGKEY}\Components"
    DeleteRegKey /IfEmpty HKLM "${REGKEY}"
    RmDir /REBOOTOK $SMPROGRAMS\$StartMenuGroup
    RmDir /REBOOTOK $INSTDIR
SectionEnd

# Installer functions
Function .onInit
    InitPluginsDir
    StrCpy $StartMenuGroup winkhouse
FunctionEnd

# Uninstaller functions
Function un.onInit
    ReadRegStr $INSTDIR HKLM "${REGKEY}" Path
    StrCpy $StartMenuGroup winkhouse
    !insertmacro SELECT_UNSECTION Main ${UNSEC0000}
FunctionEnd

# Installer Language Strings
# TODO Update the Language Strings with the appropriate translations.

LangString ^UninstallLink ${LANG_ITALIAN} "Uninstall $(^Name)"
